services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Blossom@12
      MYSQL_DATABASE: KeellsOrder
    ports:
      - "3306:3306"

  keellsorder:
    build: .
    container_name: keellsorder-app
    ports:
      - "8081:8081"
    depends_on:
      - mysql