pipeline {

    agent any

    environment {
        WORKDIR = 'KeellsSmartGrocery/Code/KeellsSmartGrocery'
    }

    stages {

        stage('Checkout SCM code correct') {

            steps {

                checkout([

                    $class: 'GitSCM',

                    branches: [[
                        name: '*/main'
                    ]],

                    extensions: [[

                        $class: 'SparseCheckoutPaths',

                        sparseCheckoutPaths: [[
                            path: 'KeellsSmartGrocery/Code/KeellsSmartGrocery'
                        ]]
                    ]],

                    userRemoteConfigs: [[
                        url: 'https://github.com/Navi-sai/Keells.git'
                    ]]
                ])
            }
        }

        stage('Build (Clean + Package)') {

            steps {

                dir("${WORKDIR}") {

                    echo 'Running Maven build...'

                    bat 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Deploy with Docker Compose') {
            
            steps {
                dir("${WORKDIR}") {

                    bat 'docker compose up -d --build'
                }
            }
        }
    }

    post {

        success {
            echo 'Build completed successfully ✔'
        }

        failure {
            echo 'Build failed ❌ Check logs'
        }
    }
}